# Dockerfile for the CRG Container Jamstats

# Base image
FROM python:3.11-slim-buster

# Metadata
LABEL author-derby-name="Breadpool"
LABEL author-legal-name="Timothy Hull"
LABEL version="1.0"

# Install updates
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-recommends -y curl libgtk-3-dev python3-pip python3-venv build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the Python pip requirements file
COPY requirements/requirements_jamstats.txt requirements/requirements_jamstats.txt

# Upgrade pip and install requirements from the requirements file
RUN python -m pip install --no-cache-dir --upgrade pip && \
    python -m pip install --no-cache-dir -r requirements/requirements_jamstats.txt && \
    rm -rf requirements

# Set build arguments
ARG CRG_MOUNT_DIR=/${CRG_MOUNT_DIR}

# Set working directory
WORKDIR ${CRG_MOUNT_DIR}

# Advertise HTTP port
EXPOSE 8080/tcp
